services:
    server:
        build:
            context: server
        tty: true
        ports:
            - 8080:8080
        expose:
            - 8080

    frontend:
        build:
            context: frontend
        ports:
            - 3000:3000
        environment:
            - NEXT_WEBPACK_USEPOLLING=1
        expose:
            - 3000
        depends_on:
            - server

    proxy:
        build:
            context: nginx
        ports:
            - 5000:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - server
            - frontend
