root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "tmp\\main.exe"
  cmd = "go build -o ./tmp/main.exe ."
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  include_dir = []
  include_ext = ["go"]
  include_file = []
